export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const HANDLE_ERRORS = 'HANDLE_ERRORS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
